/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TableFilterPaginationLazyImport = createFileRoute(
  '/table-filter-pagination',
)()
const CreateFormLazyImport = createFileRoute('/create-form')()
const ChartsLazyImport = createFileRoute('/charts')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TableFilterPaginationLazyRoute = TableFilterPaginationLazyImport.update({
  path: '/table-filter-pagination',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/table-filter-pagination.lazy').then((d) => d.Route),
)

const CreateFormLazyRoute = CreateFormLazyImport.update({
  path: '/create-form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/create-form.lazy').then((d) => d.Route))

const ChartsLazyRoute = ChartsLazyImport.update({
  path: '/charts',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/charts.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-form': {
      id: '/create-form'
      path: '/create-form'
      fullPath: '/create-form'
      preLoaderRoute: typeof CreateFormLazyImport
      parentRoute: typeof rootRoute
    }
    '/table-filter-pagination': {
      id: '/table-filter-pagination'
      path: '/table-filter-pagination'
      fullPath: '/table-filter-pagination'
      preLoaderRoute: typeof TableFilterPaginationLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  ChartsLazyRoute,
  CreateFormLazyRoute,
  TableFilterPaginationLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/charts",
        "/create-form",
        "/table-filter-pagination"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/charts": {
      "filePath": "charts.lazy.tsx"
    },
    "/create-form": {
      "filePath": "create-form.lazy.tsx"
    },
    "/table-filter-pagination": {
      "filePath": "table-filter-pagination.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
